# Generated by Django 6.1.1 on 2026-09-24 05:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_status', models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded'), ('archived', 'Archived'), ('concluded', 'Concluded')], default='active', max_length=32)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('credential_type', models.CharField(blank=True, choices=[('bcba', 'BCBA'), ('bcaba', 'BCaBA'), ('rbt', 'RBT'), ('student_analyst', 'Student Analyst')], default='', max_length=32)),
                ('org_role', models.CharField(blank=True, default='', max_length=32)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('revoked', 'Revoked')], default='pending', max_length=16)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('failed_attempts', models.PositiveIntegerField(default=0)),
                ('mfa_secret_encrypted', models.TextField(blank=True, default='')),
                ('accepted_user_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accepted_invitations', to='accounts.useraccount')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_invitations', to='accounts.useraccount')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='organizations.organization')),
            ],
            options={
                'db_table': 'user_invitation',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'email'], name='user_invita_organiz_296d87_idx')],
            },
        ),
    ]
