# Generated by Django 6.1.1 on 2026-09-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='identity',
            name='password_reset_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='identity',
            name='password_reset_code_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='identity',
            name='password_reset_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='identity',
            name='password_reset_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
