# Generated by Django 6.1 on 2026-08-27 17:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationRoleGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_status', models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded'), ('archived', 'Archived'), ('concluded', 'Concluded')], default='active', max_length=32)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(choices=[('administrator', 'Administrator'), ('clinical_director', 'Clinical Director')], max_length=32)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='organizations.organization')),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='org_role_grants', to='accounts.useraccount')),
            ],
            options={
                'db_table': 'organization_role_grant',
                'constraints': [models.UniqueConstraint(fields=('organization', 'user_account', 'role'), name='unique_org_role_grant')],
            },
        ),
    ]
