# Generated by Django 6.1 on 2026-08-27 17:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceRuleSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_status', models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded'), ('archived', 'Archived'), ('concluded', 'Concluded')], default='active', max_length=32)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('supervision_track', models.CharField(choices=[('rbt_ongoing_supervision', 'RBT Ongoing Supervision'), ('supervised_fieldwork', 'Supervised Fieldwork'), ('bcaba_ongoing_supervision', 'BCaBA Ongoing Supervision'), ('bcba_professional_development', 'BCBA Professional Development')], max_length=64)),
            ],
            options={
                'db_table': 'compliance_rule_set',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_status', models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded'), ('archived', 'Archived'), ('concluded', 'Concluded')], default='active', max_length=32)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('status', models.CharField(default='scheduled', max_length=32)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='organizations.organization')),
            ],
            options={
                'db_table': 'appointment',
            },
        ),
        migrations.CreateModel(
            name='ComplianceRuleParameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_status', models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded'), ('archived', 'Archived'), ('concluded', 'Concluded')], default='active', max_length=32)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('key', models.CharField(max_length=128)),
                ('value', models.CharField(max_length=128)),
                ('unit', models.CharField(blank=True, default='', max_length=32)),
                ('rule_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parameters', to='supervision.complianceruleset')),
            ],
            options={
                'db_table': 'compliance_rule_parameter',
            },
        ),
        migrations.CreateModel(
            name='DevelopmentPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_status', models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded'), ('archived', 'Archived'), ('concluded', 'Concluded')], default='active', max_length=32)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('plan_family_id', models.UUIDField()),
                ('version_number', models.PositiveIntegerField()),
                ('is_current', models.BooleanField(default=True)),
                ('summary', models.TextField(blank=True, default='')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='organizations.organization')),
            ],
            options={
                'db_table': 'development_plan',
            },
        ),
        migrations.CreateModel(
            name='DevelopmentPlanMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_status', models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded'), ('archived', 'Archived'), ('concluded', 'Concluded')], default='active', max_length=32)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('rationale', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', 'Active'), ('achieved', 'Achieved'), ('discontinued', 'Discontinued')], default='active', max_length=32)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='organizations.organization')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='milestones', to='supervision.developmentplan')),
            ],
            options={
                'db_table': 'development_plan_milestone',
            },
        ),
        migrations.CreateModel(
            name='MonthlyCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_status', models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded'), ('archived', 'Archived'), ('concluded', 'Concluded')], default='active', max_length=32)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('status', models.CharField(default='active', max_length=32)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='organizations.organization')),
            ],
            options={
                'db_table': 'monthly_cycle',
            },
        ),
        migrations.CreateModel(
            name='HoursEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_status', models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded'), ('archived', 'Archived'), ('concluded', 'Concluded')], default='active', max_length=32)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('attested_on', models.DateField()),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='organizations.organization')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hours_entries', to='supervision.monthlycycle')),
            ],
            options={
                'db_table': 'hours_entry',
            },
        ),
        migrations.CreateModel(
            name='ComplianceReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_status', models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded'), ('archived', 'Archived'), ('concluded', 'Concluded')], default='active', max_length=32)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField()),
                ('status', models.CharField(default='open', max_length=32)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='organizations.organization')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reminders', to='supervision.monthlycycle')),
            ],
            options={
                'db_table': 'compliance_reminder',
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_status', models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded'), ('archived', 'Archived'), ('concluded', 'Concluded')], default='active', max_length=32)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('instructions', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='issued', max_length=32)),
                ('evidence_notes', models.TextField(blank=True, default='')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='organizations.organization')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='supervision.monthlycycle')),
            ],
            options={
                'db_table': 'assignment',
            },
        ),
        migrations.CreateModel(
            name='PreSupervisionNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_status', models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded'), ('archived', 'Archived'), ('concluded', 'Concluded')], default='active', max_length=32)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('body', models.TextField()),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prep_notes', to='supervision.appointment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='organizations.organization')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prep_notes', to='accounts.useraccount')),
            ],
            options={
                'db_table': 'pre_supervision_note',
            },
        ),
        migrations.CreateModel(
            name='SupervisionSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_status', models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded'), ('archived', 'Archived'), ('concluded', 'Concluded')], default='active', max_length=32)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('occurred_on', models.DateField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True, default='')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='supervision.monthlycycle')),
                ('documented_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documented_sessions', to='accounts.useraccount')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='organizations.organization')),
            ],
            options={
                'db_table': 'supervision_session',
            },
        ),
        migrations.CreateModel(
            name='SupervisoryRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_status', models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded'), ('archived', 'Archived'), ('concluded', 'Concluded')], default='active', max_length=32)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('supervision_track', models.CharField(choices=[('rbt_ongoing_supervision', 'RBT Ongoing Supervision'), ('supervised_fieldwork', 'Supervised Fieldwork'), ('bcaba_ongoing_supervision', 'BCaBA Ongoing Supervision'), ('bcba_professional_development', 'BCBA Professional Development')], max_length=64)),
                ('fieldwork_subtype', models.CharField(blank=True, choices=[('supervised', 'Supervised'), ('concentrated', 'Concentrated')], default='', max_length=32)),
                ('started_on', models.DateField()),
                ('ended_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=32)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='organizations.organization')),
                ('supervisee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supervisee_relationships', to='accounts.useraccount')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supervised_relationships', to='accounts.useraccount')),
            ],
            options={
                'db_table': 'supervisory_relationship',
            },
        ),
        migrations.CreateModel(
            name='SuperviseeIntake',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_status', models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded'), ('archived', 'Archived'), ('concluded', 'Concluded')], default='active', max_length=32)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('captured_on', models.DateField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='organizations.organization')),
                ('relationship', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='intake', to='supervision.supervisoryrelationship')),
            ],
            options={
                'db_table': 'supervisee_intake',
            },
        ),
        migrations.CreateModel(
            name='ReviewComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_status', models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded'), ('archived', 'Archived'), ('concluded', 'Concluded')], default='active', max_length=32)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('body', models.TextField()),
                ('target_entity_type', models.CharField(max_length=64)),
                ('target_entity_id', models.UUIDField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_comments', to='accounts.useraccount')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='organizations.organization')),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_comments', to='supervision.supervisoryrelationship')),
            ],
            options={
                'db_table': 'review_comment',
            },
        ),
        migrations.CreateModel(
            name='RelationshipConclusion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_status', models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded'), ('archived', 'Archived'), ('concluded', 'Concluded')], default='active', max_length=32)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(max_length=255)),
                ('concluded_on', models.DateField()),
                ('notes', models.TextField(blank=True, default='')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='organizations.organization')),
                ('relationship', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='conclusion', to='supervision.supervisoryrelationship')),
            ],
            options={
                'db_table': 'relationship_conclusion',
            },
        ),
        migrations.AddField(
            model_name='monthlycycle',
            name='relationship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_cycles', to='supervision.supervisoryrelationship'),
        ),
        migrations.AddField(
            model_name='developmentplan',
            name='relationship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='development_plans', to='supervision.supervisoryrelationship'),
        ),
        migrations.CreateModel(
            name='CompetencyAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_status', models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded'), ('archived', 'Archived'), ('concluded', 'Concluded')], default='active', max_length=32)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('assessed_on', models.DateField()),
                ('rating_scale', models.CharField(max_length=64)),
                ('rating', models.CharField(max_length=64)),
                ('documented_content', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='organizations.organization')),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='supervision.supervisoryrelationship')),
            ],
            options={
                'db_table': 'competency_assessment',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='relationship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='supervision.supervisoryrelationship'),
        ),
        migrations.CreateModel(
            name='AISuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_status', models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded'), ('archived', 'Archived'), ('concluded', 'Concluded')], default='active', max_length=32)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('suggestion_identifier', models.UUIDField(unique=True)),
                ('prompt', models.TextField()),
                ('model_name', models.CharField(max_length=128)),
                ('explanation', models.TextField()),
                ('disposition', models.CharField(default='pending', max_length=32)),
                ('dispositioned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ai_dispositions', to='accounts.useraccount')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='organizations.organization')),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_suggestions', to='supervision.supervisoryrelationship')),
            ],
            options={
                'db_table': 'ai_suggestion',
            },
        ),
        migrations.AddConstraint(
            model_name='supervisoryrelationship',
            constraint=models.CheckConstraint(condition=models.Q(('supervisor', models.F('supervisee')), _negated=True), name='relationship_supervisor_ne_supervisee'),
        ),
        migrations.AddConstraint(
            model_name='monthlycycle',
            constraint=models.UniqueConstraint(fields=('relationship', 'year', 'month'), name='unique_cycle_per_relationship_month'),
        ),
        migrations.AddConstraint(
            model_name='developmentplan',
            constraint=models.UniqueConstraint(fields=('plan_family_id', 'version_number'), name='unique_idp_version'),
        ),
    ]
