# Generated by Django 6.1

import django.db.models.deletion
import uuid
from django.db import migrations, models


def backfill_bcba_supervisee_purpose(apps, schema_editor):
    Relationship = apps.get_model("supervision", "SupervisoryRelationship")
    UserAccount = apps.get_model("accounts", "UserAccount")
    bcba_ids = UserAccount.objects.filter(credential_type="bcba").values_list("id", flat=True)
    Relationship.objects.filter(supervisee_id__in=bcba_ids, supervisee_purpose="").update(
        supervisee_purpose="structured_professional_development",
        supervision_track="bcba_professional_development",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("organizations", "0001_initial"),
        ("supervision", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="supervisoryrelationship",
            name="supervisee_purpose",
            field=models.CharField(
                blank=True,
                choices=[
                    ("structured_professional_development", "Structured professional development"),
                    ("consultation", "Consultation"),
                    ("competency_development", "Competency development"),
                    ("leadership_development", "Leadership development"),
                    ("case_discussion", "Case discussion"),
                ],
                default="",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="superviseeintake",
            name="background",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="superviseeintake",
            name="current_credential",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="superviseeintake",
            name="starting_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="developmentplanmilestone",
            name="sort_order",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="DevelopmentPlanGoal",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "record_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("superseded", "Superseded"),
                            ("archived", "Archived"),
                            ("concluded", "Concluded"),
                        ],
                        default="active",
                        max_length=32,
                    ),
                ),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("status", models.CharField(default="active", max_length=32)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="organizations.organization",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="goals",
                        to="supervision.developmentplan",
                    ),
                ),
            ],
            options={
                "db_table": "development_plan_goal",
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="DevelopmentPlanCompetency",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "record_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("superseded", "Superseded"),
                            ("archived", "Archived"),
                            ("concluded", "Concluded"),
                        ],
                        default="active",
                        max_length=32,
                    ),
                ),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("target_level", models.CharField(blank=True, default="", max_length=64)),
                ("current_level", models.CharField(blank=True, default="", max_length=64)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="organizations.organization",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="competencies",
                        to="supervision.developmentplan",
                    ),
                ),
            ],
            options={
                "db_table": "development_plan_competency",
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="developmentplan",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("plan_family_id",),
                name="unique_current_idp_per_family",
            ),
        ),
        migrations.RunPython(backfill_bcba_supervisee_purpose, migrations.RunPython.noop),
    ]
