# Generated by Django 6.1.1 on 2026-09-16 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0002_supervision_setup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developmentplanmilestone',
            options={'ordering': ['sort_order', 'created_at']},
        ),
    ]
