# Generated by Django 6.1.1 on 2026-09-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0003_alter_developmentplanmilestone_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='developmentplangoal',
            name='category',
            field=models.CharField(blank=True, choices=[('data_collection', 'Data Collection & Measurement'), ('clinical_documentation', 'Clinical Documentation'), ('skill_acquisition', 'Skill Acquisition'), ('behavior_reduction', 'Behavior Reduction'), ('reinforcement', 'Reinforcement'), ('prompting', 'Prompting & Prompt Fading'), ('functional_communication', 'Functional Communication'), ('generalization_maintenance', 'Generalization & Maintenance'), ('treatment_integrity', 'Treatment Integrity'), ('professional_communication', 'Professional Communication'), ('stakeholder_collaboration', 'Caregiver/Stakeholder Collaboration'), ('ethics', 'Ethics & Professional Conduct'), ('clinical_reasoning', 'Clinical Reasoning'), ('session_preparation', 'Session Preparation & Organization'), ('professional_growth', 'Professional Growth'), ('other', 'Other')], default='', max_length=64),
        ),
        migrations.AddField(
            model_name='superviseeintake',
            name='current_context',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='superviseeintake',
            name='current_context_other',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='superviseeintake',
            name='further_assessment_needed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='superviseeintake',
            name='prior_aba_experience',
            field=models.CharField(blank=True, choices=[('none', 'No prior ABA experience'), ('some', 'Some prior ABA experience'), ('rbt', 'Prior RBT experience'), ('bcaba', 'Prior BCaBA experience'), ('other', 'Other ABA experience'), ('not_determined', 'Not yet determined')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='superviseeintake',
            name='prior_aba_experience_other',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='superviseeintake',
            name='starting_domains',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='superviseeintake',
            name='starting_domains_other',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='developmentplancompetency',
            name='current_level',
            field=models.CharField(blank=True, choices=[('not_yet_assessed', 'Not Yet Assessed'), ('needs_training', 'Needs Training'), ('developing', 'Developing'), ('performs_with_support', 'Performs With Support'), ('independent', 'Independent')], default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='developmentplancompetency',
            name='target_level',
            field=models.CharField(blank=True, choices=[('not_yet_assessed', 'Not Yet Assessed'), ('needs_training', 'Needs Training'), ('developing', 'Developing'), ('performs_with_support', 'Performs With Support'), ('independent', 'Independent')], default='', max_length=64),
        ),
    ]
