# Generated by Django 6.1.1 on 2026-09-30 16:24

from django.db import migrations, models


def unanswered_assessment_flag(apps, schema_editor):
    # Until now this was an unchecked-by-default checkbox, so False never recorded an explicit "No"
    SuperviseeIntake = apps.get_model("supervision", "SuperviseeIntake")
    SuperviseeIntake.objects.filter(further_assessment_needed=False).update(further_assessment_needed=None)


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0004_structured_intake_and_plan_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='developmentplancompetency',
            name='competency_key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='developmentplancompetency',
            name='domain',
            field=models.CharField(blank=True, choices=[('data_collection', 'Data Collection & Measurement'), ('clinical_documentation', 'Clinical Documentation'), ('skill_acquisition', 'Skill Acquisition'), ('behavior_reduction', 'Behavior Reduction'), ('reinforcement', 'Reinforcement'), ('prompting', 'Prompting & Prompt Fading'), ('functional_communication', 'Functional Communication'), ('generalization_maintenance', 'Generalization & Maintenance'), ('treatment_integrity', 'Treatment Integrity'), ('professional_communication', 'Professional Communication'), ('stakeholder_collaboration', 'Caregiver/Stakeholder Collaboration'), ('ethics', 'Ethics & Professional Conduct'), ('clinical_reasoning', 'Clinical Reasoning'), ('session_preparation', 'Session Preparation & Organization'), ('other', 'Other')], default='', max_length=64),
        ),
        migrations.AddField(
            model_name='developmentplancompetency',
            name='pathways',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='developmentplanmilestone',
            name='criterion_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='developmentplanmilestone',
            name='template_key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='superviseeintake',
            name='further_assessment_needed',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.RunPython(unanswered_assessment_flag, migrations.RunPython.noop),
    ]
