# Generated by Django 6.1.2 on 2026-10-08 12:00

import apps.supervision.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


def backfill(apps, schema_editor):
    """Rows from before this migration: the day worked is the day attested, a verified entry
    keeps its status, and a fieldwork month takes the relationship's fieldwork subtype."""
    HoursEntry = apps.get_model("supervision", "HoursEntry")
    MonthlyCycle = apps.get_model("supervision", "MonthlyCycle")
    for entry in HoursEntry.objects.filter(occurred_on__isnull=True):
        entry.occurred_on = entry.attested_on
        entry.status = "verified" if entry.verified else "pending"
        entry.save(update_fields=["occurred_on", "status"])
    for cycle in MonthlyCycle.objects.filter(
        fieldwork_type="", relationship__supervision_track="supervised_fieldwork"
    ).select_related("relationship"):
        cycle.fieldwork_type = cycle.relationship.fieldwork_subtype or "supervised"
        cycle.save(update_fields=["fieldwork_type"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_identity_password_reset'),
        ('organizations', '0001_initial'),
        ('supervision', '0005_milestone_templates_competency_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='hoursentry',
            options={'ordering': ['occurred_on', 'created_at']},
        ),
        migrations.AlterModelOptions(
            name='monthlycycle',
            options={'ordering': ['year', 'month']},
        ),
        migrations.AlterModelOptions(
            name='supervisionsession',
            options={'ordering': ['occurred_on', 'created_at']},
        ),
        migrations.AddField(
            model_name='assignment',
            name='due_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issued_assignments', to='accounts.useraccount'),
        ),
        migrations.AddField(
            model_name='hoursentry',
            name='client_observation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hoursentry',
            name='kind',
            field=models.CharField(choices=[('independent', 'Independent Fieldwork'), ('supervision', 'Supervision')], default='independent', max_length=32),
        ),
        migrations.AddField(
            model_name='hoursentry',
            name='logged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logged_hours', to='accounts.useraccount'),
        ),
        migrations.AddField(
            model_name='hoursentry',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='hoursentry',
            name='occurred_on',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='hoursentry',
            name='return_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='hoursentry',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified'), ('returned', 'Returned for Correction')], default='pending', max_length=32),
        ),
        migrations.AddField(
            model_name='hoursentry',
            name='supervision_format',
            field=models.CharField(blank=True, choices=[('individual', 'Individual'), ('group', 'Group')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='hoursentry',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_hours', to='accounts.useraccount'),
        ),
        migrations.AddField(
            model_name='monthlycycle',
            name='fieldwork_type',
            field=models.CharField(blank=True, choices=[('supervised', 'Supervised'), ('concentrated', 'Concentrated')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='supervisionsession',
            name='client_observation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supervisionsession',
            name='session_type',
            field=models.CharField(choices=[('individual', 'Individual Supervision'), ('group', 'Group Supervision')], default='individual', max_length=32),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('issued', 'Issued'), ('submitted', 'Submitted'), ('revision_requested', 'Revision Requested'), ('completed', 'Completed')], default='issued', max_length=32),
        ),
        migrations.CreateModel(
            name='AssignmentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_status', models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded'), ('archived', 'Archived'), ('concluded', 'Concluded')], default='active', max_length=32)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('from_status', models.CharField(blank=True, choices=[('issued', 'Issued'), ('submitted', 'Submitted'), ('revision_requested', 'Revision Requested'), ('completed', 'Completed')], default='', max_length=32)),
                ('to_status', models.CharField(choices=[('issued', 'Issued'), ('submitted', 'Submitted'), ('revision_requested', 'Revision Requested'), ('completed', 'Completed')], max_length=32)),
                ('comment', models.TextField(blank=True, default='')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignment_events', to='accounts.useraccount')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='supervision.assignment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='organizations.organization')),
            ],
            options={
                'db_table': 'assignment_event',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_status', models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded'), ('archived', 'Archived'), ('concluded', 'Concluded')], default='active', max_length=32)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(max_length=500, upload_to=apps.supervision.models._attachment_path)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=128)),
                ('size_bytes', models.PositiveIntegerField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='supervision.assignment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='organizations.organization')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignment_attachments', to='accounts.useraccount')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='supervision.assignmentevent')),
            ],
            options={
                'db_table': 'assignment_attachment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceHoursAttestation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_status', models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded'), ('archived', 'Archived'), ('concluded', 'Concluded')], default='active', max_length=32)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=7)),
                ('attested_on', models.DateField()),
                ('notes', models.TextField(blank=True, default='')),
                ('attested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_attestations', to='accounts.useraccount')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_attestations', to='supervision.monthlycycle')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='organizations.organization')),
            ],
            options={
                'db_table': 'service_hours_attestation',
                'constraints': [models.UniqueConstraint(fields=('cycle',), name='unique_service_attestation_per_cycle')],
            },
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
